printWidth: 80
trailingComma: 'all'
singleQuote: true
semi: true
arrowParens: 'always'

plugins:
  - '@ianvs/prettier-plugin-sort-imports'
importOrder:
  [
    '<BUILTIN_MODULES>',
    '<THIRD_PARTY_MODULES>',
    '',
    '^#/(.*)$',
    '^[./]',
    '',
    '^public/(.*)$',
  ]
importOrderParserPlugins: [ 'typescript', 'jsx', 'decorators-legacy' ]
importOrderTypeScriptVersion: '5.0.0'
